### ISSUE TITLE
These are not working

### ISSUE THREAD

**Issue by excennfahnfah1976** [dphn/ScContent#1]
```
   'ScContent',
    'ScWidgets',
```

**Comment by excennfahnfah1976** [comment]
Strict Standards: Declaration of ScContent\Module::init() should be compatible with ZfcBase\Module\AbstractModule::init(Zend\ModuleManager\ModuleManager $moduleManager) in /var/www/zf2-tutorial/vendor/dphn/sc-content/Module.php on line 27 Fatal error: Uncaught exception 'Zend\ServiceManager\Exception\InvalidServiceNameException' with message 'An alias by the name "zenddbadapteradapter" or "Zend\Db\Adapter\Adapter" already exists' in /var/www/zf2-tutorial/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php:801 Stack trace: #0 /var/www/zf2-tutorial/vendor/zendframework/zendframework/library/Zend/ServiceManager/Config.php(149): Zend\ServiceManager\ServiceManager->setAlias('Zend\Db\Adapter...', 'ScDb.Adapter') #1 /var/www/zf2-tutorial/vendor/zendframework/zendframework/library/Zend/ModuleManager/Listener/ServiceListener.php(223): Zend\ServiceManager\Config->configureServiceManager(Object(Zend\ServiceManager\ServiceManager)) #2 [internal function]: Zend\ModuleManager\Listener\ServiceListener->onLoadModulesPost(Object(Zend\ModuleManager\ModuleEvent)) #3 /var/www/zf2-tutorial/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\ModuleManager\ModuleEvent)) #4 /var/www/zf in /var/www/zf2-tutorial/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 801
